### ISSUE TITLE
minikube profile devnation

### ISSUE THREAD

**Issue by burrsutter** [redhat-scholars/kubernetes-tutorial#19]
This page forgets to tell the reader that the need to make the profile name "stick"
https://redhat-developer-demos.github.io/kubernetes-tutorial/kubernetes-tutorial/installation.html#start-minikube
using
minikube profile devnation

as subsequent examples refer to:
minikube ip
which needs to know the profile

**Comment by kameshsampath** [comment]
@burrsutter  @lordofthejars  - the minikube profile will be removed soon and when we start `minkube -p deviation start` this will automatically set the current profile to deviation and we don't need extra `minikube profile devnation`
