### ISSUE TITLE
Using Ingress

### ISSUE THREAD

**Issue by kameshsampath** [redhat-scholars/kubernetes-tutorial#27]
With this project projectcontour.io incubating into CNCF, it will be nice for us to show the users about Ingress. This Ingress is based on envoy so the elements are just same as virtual service

@burrsutter  @lordofthejars  thoughts ??

**Comment by burrsutter** [comment]
We would like to keep the Minikube and Openshift experiences fairly close.  If you deploy the nginx based ingress to minikube (and nginx is the most popular solution) then the Ingress.yaml used is close to the Ingress.yaml used on OpenShift which generates a Route via ha-proxy.

**Comment by kameshsampath** [comment]
@burrsutter are you saying we add it or not?? I quoted projectcontour because its part of CNCF and it understands kubernetes Ingress resource.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by burrsutter** [comment]
let's stick with nginx and its minikube add-on 
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/
